name: paisa
description: A expense manager app for Android, iOS, Web & Windows.

publish_to: "none"

version: 4.8.0+480

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  animations: ^2.0.7
  bezier_chart_plus: ^0.0.1
  chart_sparkline: ^1.0.13
  collection: ^1.17.0
  csv: ^5.0.1
  dartz: ^0.10.1
  date_picker_timeline: ^1.2.3
  device_info_plus:
  dynamic_color: ^1.6.5
  equatable: ^2.0.5
  file_picker: ^5.2.5
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.0.0
  get_it: ^7.2.0
  glassmorphism: ^3.0.0
  go_router: ^9.0.1 #//5.1.1
  google_fonts: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.0
  in_app_review: ^2.0.6
  in_app_update: ^4.1.4
  injectable: ^2.1.0
  intl: ^0.18.0
  local_auth: ^2.1.3
  material_color_utilities: ^0.2.0
  material_design_icons_flutter: ^7.0.7296
  package_info_plus: ^4.0.2
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  provider: ^6.0.5
  quick_actions: ^1.0.2
  responsive_builder: 0.5.0+1
  share_plus: ^7.0.2
  url_launcher: ^6.1.7
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.3.2
  change_app_package_name: any
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.0+1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.4

dependency_overrides:
  intl: ^0.18.0
  material_color_utilities: ^0.2.0

flutter_app_name:
  name: "Paisa"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon.png
  color_dark: "#121212"
  android: true
  ios: true
  android_12:
    image: assets/images/icon_light.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/icon_dark.png
    icon_background_color_dark: "#121212"

flutter_icons:
  ios: true
  android: false
  image_path: "assets/images/icon.png"
  image_path_ios: "assets/images/ios_app_icon.png"
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
