# name: Android Build & Release
# on:
#   push:
#     branches:
#       - master
# jobs:
#   build_apk:
#     name: Build Flutter APK
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-java@v1
#         with:
#           java-version: "12.x"
#       - uses: subosito/flutter-action@v1
#         with:
#           channel: "stable"
#       - name: Download Android keystore
#         id: android_keystore
#         uses: timheuer/base64-to-file@v1.0.3
#         with:
#           fileName: key.jks
#           encodedString: ${{ secrets.KEYSTORE }}
#       - name: Create key.properties
#         run: |
#           echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
#           echo "storePassword=${{ secrets.SIGNING_STORE_PASSWORD }}" >> android/key.properties
#           echo "keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}" >> android/key.properties
#           echo "keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}" >> android/key.properties
#       - name: Run build release apk
#         run: flutter build --release --flavor prod
#       - name: Push to Releases
#         uses: ncipollo/release-action@v1
#         with:
#           artifacts: "build/app/outputs/flutter-apk/*"
#           tag: v4.0.${{ github.run_number }}
